---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: potato
  template:
    metadata:
      labels:
        app: potato
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: potato
  ports:
    - port: 80
      targetPort: 80
